# Copyright (c) 2025-2026 Netresearch DTT GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
