# Makefile for rte_ckeditor_image TYPO3 Extension
# Auto-generated by agent - Last updated: 2025-10-22

.PHONY: help
help: ## Show available targets
	@awk 'BEGIN{FS=":.*##";print "\nUsage: make <target>\n"} /^[a-zA-Z0-9_.-]+:.*##/ {printf "  %-22s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# ===================================
# DDEV Environment Commands
# ===================================

.PHONY: up
up: ## Complete startup (start DDEV + run setup) - ONE COMMAND TO RULE THEM ALL
	@echo "🚀 Starting DDEV environment..."
	@ddev start
	@echo ""
	@echo "🔧 Running setup (docs + v13 + v14)..."
	@ddev setup

.PHONY: start
start: ## Start DDEV environment
	ddev start

.PHONY: stop
stop: ## Stop DDEV environment
	ddev stop

.PHONY: setup
setup: ## Complete setup (docs + install v13 + install v14)
	@ddev describe >/dev/null 2>&1 || ddev start
	ddev setup

.PHONY: docs
docs: ## Render extension documentation
	ddev docs

.PHONY: docs-lint
docs-lint: ## Lint documentation (TYPO3 guidelines compliance)
	./Build/Scripts/validate-docs.sh

.PHONY: docs-fix
docs-fix: ## Fix auto-fixable documentation issues
	./Build/Scripts/validate-docs.sh --fix

.PHONY: install-v13
install-v13: ## Install TYPO3 v13.4 LTS
	ddev install-v13

.PHONY: install-v14
install-v14: ## Install TYPO3 v14.0
	ddev install-v14

.PHONY: ddev-restart
ddev-restart: ## Restart DDEV containers
	ddev restart

# ===================================
# Composer & Quality Commands
# ===================================

.PHONY: install
install: ## Install composer dependencies
	composer install

.PHONY: lint
lint: ## Run all linters (PHP syntax + PHPStan + style check + docs)
	@echo "==> Running PHP lint..."
	composer ci:test:php:lint
	@echo "==> Running PHPStan..."
	composer ci:test:php:phpstan
	@echo "==> Running Rector check..."
	composer ci:test:php:rector
	@echo "==> Running code style check..."
	composer ci:test:php:cgl
	@echo "==> Running documentation lint..."
	./Build/Scripts/validate-docs.sh || true
	@echo "✅ All linters passed"

.PHONY: format
format: ## Auto-fix code style issues
	composer ci:cgl

.PHONY: typecheck
typecheck: ## Run PHPStan static analysis
	composer ci:test:php:phpstan

.PHONY: rector
rector: ## Apply Rector PHP modernization changes
	composer ci:rector

.PHONY: rector-check
rector-check: ## Check Rector suggestions without applying
	composer ci:test:php:rector

.PHONY: test
test: ## Run tests (when available)
	@echo "⚠️  Tests not yet configured"
	@echo "See Tests/AGENTS.md for test setup instructions"

.PHONY: ci
ci: ## Run complete CI pipeline (pre-commit checks)
	composer ci:test

.PHONY: phpstan-baseline
phpstan-baseline: ## Update PHPStan baseline
	composer ci:test:php:phpstan:baseline

.PHONY: clean
clean: ## Clean temporary files and caches
	rm -rf .php-cs-fixer.cache
	rm -rf var/

.DEFAULT_GOAL := help
