# Makefile for rte_ckeditor_image TYPO3 Extension
# Auto-generated by agent - Last updated: 2025-10-15

.PHONY: help
help: ## Show available targets
	@awk 'BEGIN{FS=":.*##";print "\nUsage: make <target>\n"} /^[a-zA-Z0-9_.-]+:.*##/ {printf "  %-22s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

.PHONY: install
install: ## Install composer dependencies
	composer install

.PHONY: lint
lint: ## Run all linters (PHP syntax + PHPStan + style check)
	@echo "==> Running PHP lint..."
	composer ci:test:php:lint
	@echo "==> Running PHPStan..."
	composer ci:test:php:phpstan
	@echo "==> Running Rector check..."
	composer ci:test:php:rector
	@echo "==> Running code style check..."
	composer ci:test:php:cgl
	@echo "✅ All linters passed"

.PHONY: format
format: ## Auto-fix code style issues
	composer ci:cgl

.PHONY: typecheck
typecheck: ## Run PHPStan static analysis
	composer ci:test:php:phpstan

.PHONY: rector
rector: ## Apply Rector PHP modernization changes
	composer ci:rector

.PHONY: rector-check
rector-check: ## Check Rector suggestions without applying
	composer ci:test:php:rector

.PHONY: test
test: ## Run tests (when available)
	@echo "⚠️  Tests not yet configured"
	@echo "See Tests/AGENTS.md for test setup instructions"

.PHONY: ci
ci: ## Run complete CI pipeline (pre-commit checks)
	composer ci:test

.PHONY: phpstan-baseline
phpstan-baseline: ## Update PHPStan baseline
	composer ci:test:php:phpstan:baseline

.PHONY: clean
clean: ## Clean temporary files and caches
	rm -rf .php-cs-fixer.cache
	rm -rf var/

.DEFAULT_GOAL := help
