#!/usr/bin/env sh

# Copyright (c) 2025-2026 Netresearch DTT GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

# Validate ext_emconf.php version matches any semver tag at HEAD
Build/Scripts/check-tag-version.sh
