# Copyright (c) 2025-2026 Netresearch DTT GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  web:
    build:
      args:
        GIT_BRANCH: "feature/fluid-templates-refactoring-planning"
        GIT_COMMIT: "ec13a71"
        GIT_PR: "418"
